import { StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing } from '@/src/shared/theme';

export const styles = StyleSheet.create({
  content: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xxl,
    backgroundColor: colors.bg,
  },
  soundToggle: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    height: 44,
    justifyContent: 'center',
    width: 44,
    ...shadow,
  },
  soundToggleActive: {
  },
  timerCircleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.xl,
    position: 'relative',
  },
  timerCircle: {
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow,
    shadowOpacity: 0.1,
    shadowRadius: 20,
  },
  glow: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    opacity: 0.5,
  },
  timeText: {
    color: colors.text,
    fontSize: 64,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
    letterSpacing: -2,
  },
  panel: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    ...shadow,
    marginBottom: spacing.lg,
  },
  timeInfoGrid: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.md,
  },
  infoCard: {
    flex: 1,
    gap: 4,
    alignItems: 'center',
  },
  infoLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  infoValue: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  sectionTitle: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  inputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  minuteInput: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    color: colors.text,
    flex: 1,
    fontSize: 20,
    fontWeight: '700',
    minHeight: 54,
    paddingHorizontal: spacing.lg,
    textAlign: 'center',
  },
  inputUnit: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  presets: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  presetButton: {
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    borderColor: 'transparent',
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 46,
    minWidth: 62,
  },
  presetButtonSelected: {
  },
  presetText: {
    color: colors.textSoft,
    fontSize: 16,
    fontWeight: '700',
  },
  presetTextSelected: {
    color: colors.primary,
  },
  actions: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: 'auto',
  },
  primaryAction: {
    flex: 2,
    height: 60,
    borderRadius: radius.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...shadow,
  },
  primaryActionText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  secondaryAction: {
    width: 60,
    height: 60,
    borderRadius: radius.xl,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow,
  },
  disabled: {
    opacity: 0.5,
  },
});
